-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customer"
(
    customer_id smallserial,
    last_name character varying(30) NOT NULL,
    first_name character varying(30) NOT NULL,
    address text,
    email character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    password character varying(60) NOT NULL,
    PRIMARY KEY (customer_id),
    CONSTRAINT email_uniqueness UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."Order"
(
    order_id smallserial,
    customer_id smallserial,
    price money NOT NULL,
    email character varying(50) NOT NULL,
    date date NOT NULL,
    total_items smallint NOT NULL,
    shipping_address text NOT NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public."Cart"
(
    cart_id smallserial,
    customer_id smallserial,
    order_id smallserial,
    product_id smallserial NOT NULL,
    product_count smallint NOT NULL,
    PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    product_id smallserial,
    name character varying(30) NOT NULL,
    price money NOT NULL,
    description text,
    image text,
    PRIMARY KEY (product_id)
);

ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT "foreign keys" FOREIGN KEY (customer_id)
    REFERENCES public."Customer" (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cart"
    ADD CONSTRAINT customer_fk FOREIGN KEY (customer_id)
    REFERENCES public."Customer" (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cart"
    ADD CONSTRAINT order_fk FOREIGN KEY (order_id)
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cart"
    ADD CONSTRAINT product_fk FOREIGN KEY (product_id)
    REFERENCES public."Product" (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;